In [ ]:
# %pip install pyannote.audio
# %pip install numpy==1.26

Requirement already satisfied: pyannote.audio in c:\Users\a\LLM\ch05dia\Lib\site-packages (3.1.1)
Requirement already satisfied: asteroid-filterbanks>=0.4 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (0.4.0)
Requirement already satisfied: einops>=0.6.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (0.8.2)
Requirement already satisfied: huggingface-hub>=0.13.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (0.19.4)
Requirement already satisfied: lightning>=2.0.1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (2.6.1)
Requirement already satisfied: omegaconf<3.0,>=2.1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (2.3.0)
Requirement already satisfied: pyannote.core>=5.0.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (6.0.1)
Requirement already satisfied: pyannote.database>=5.0.1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (6.1.1)
Requirement already satisfied: pyannote.metrics>=3.2 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (4.0.0)
Requirement already satisfied: pyannote.pipeline>=3.0.1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (4.0.0)
Requirement already satisfied: pytorch-metric-learning>=2.1.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (2.9.0)
Requirement already satisfied: rich>=12.0.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (15.0.0)
Requirement already satisfied: semver>=3.0.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (3.0.4)
Requirement already satisfied: soundfile>=0.12.1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (0.13.1)
Requirement already satisfied: speechbrain>=0.5.14 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (1.1.0)
Requirement already satisfied: tensorboardX>=2.6 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (2.6.5)
Requirement already satisfied: torch>=2.0.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (2.1.2+cpu)
Requirement already satisfied: torch-audiomentations>=0.11.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (0.12.0)
Requirement already satisfied: torchaudio>=2.0.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (2.1.2+cpu)
Requirement already satisfied: torchmetrics>=0.11.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.audio) (1.9.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\Users\a\LLM\ch05dia\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio) (6.0.3)
Requirement already satisfied: numpy in c:\Users\a\LLM\ch05dia\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio) (1.26.0)
Requirement already satisfied: typing-extensions in c:\Users\a\LLM\ch05dia\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio) (4.15.0)
Requirement already satisfied: filelock in c:\Users\a\LLM\ch05dia\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio) (2026.2.0)
Requirement already satisfied: requests in c:\Users\a\LLM\ch05dia\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio) (2.28.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio) (4.67.3)
Requirement already satisfied: packaging>=20.9 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio) (26.2)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from lightning>=2.0.1->pyannote.audio) (0.15.3)
Requirement already satisfied: pytorch-lightning in c:\Users\a\LLM\ch05dia\Lib\site-packages (from lightning>=2.0.1->pyannote.audio) (2.6.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio) (3.13.5)
Requirement already satisfied: sympy in c:\Users\a\LLM\ch05dia\Lib\site-packages (from torch>=2.0.0->pyannote.audio) (1.14.0)
Requirement already satisfied: networkx in c:\Users\a\LLM\ch05dia\Lib\site-packages (from torch>=2.0.0->pyannote.audio) (3.6.1)
Requirement already satisfied: jinja2 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from torch>=2.0.0->pyannote.audio) (3.1.6)
Requirement already satisfied: colorama in c:\Users\a\LLM\ch05dia\Lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.13.0->pyannote.audio) (0.4.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio) (1.23.0)
Requirement already satisfied: idna>=2.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio) (3.13)
Collecting numpy (from asteroid-filterbanks>=0.4->pyannote.audio)
  Using cached numpy-2.4.4-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: pandas>=2.2.3 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio) (3.0.2)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio) (2026.2)
Requirement already satisfied: scikit-learn>=1.6.1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio) (1.8.0)
Requirement already satisfied: scipy>=1.15.1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio) (1.17.1)
Requirement already satisfied: optuna>=4.2.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from pyannote.pipeline>=3.0.1->pyannote.audio) (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio) (1.18.4)
Requirement already satisfied: colorlog in c:\Users\a\LLM\ch05dia\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio) (2.0.49)
Requirement already satisfied: Mako in c:\Users\a\LLM\ch05dia\Lib\site-packages (from alembic>=1.5.0->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio) (1.3.12)
Requirement already satisfied: six>=1.5 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from rich>=12.0.0->pyannote.audio) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from rich>=12.0.0->pyannote.audio) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.0.0->pyannote.audio) (0.1.2)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio) (3.6.0)
Requirement already satisfied: cffi>=1.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from soundfile>=0.12.1->pyannote.audio) (2.0.0)
Requirement already satisfied: pycparser in c:\Users\a\LLM\ch05dia\Lib\site-packages (from cffi>=1.0->soundfile>=0.12.1->pyannote.audio) (3.0)
Requirement already satisfied: hyperpyyaml>=0.0.1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio) (1.2.3)
Requirement already satisfied: sentencepiece>=0.1.91 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio) (0.2.1)
Requirement already satisfied: ruamel.yaml<0.19.0,>=0.17.28 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio) (0.18.17)
Requirement already satisfied: ruamel.yaml.clib>=0.2.15 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from ruamel.yaml<0.19.0,>=0.17.28->hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio) (0.2.15)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio) (2026.4.22)
Requirement already satisfied: greenlet>=1 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from sqlalchemy>=1.4.2->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio) (3.5.0)
Requirement already satisfied: protobuf>=3.20 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from tensorboardX>=2.6->pyannote.audio) (7.34.1)
Requirement already satisfied: julius<0.3,>=0.2.3 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio) (0.2.7)
Requirement already satisfied: torch-pitch-shift>=1.2.2 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio) (1.2.5)
Requirement already satisfied: primePy>=1.3 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from torch-pitch-shift>=1.2.2->torch-audiomentations>=0.11.0->pyannote.audio) (1.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from jinja2->torch>=2.0.0->pyannote.audio) (3.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from sympy->torch>=2.0.0->pyannote.audio) (1.3.0)
Using cached numpy-2.4.4-cp311-cp311-win_amd64.whl (12.6 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.0
    Uninstalling numpy-1.26.0:
      Successfully uninstalled numpy-1.26.0
Successfully installed numpy-2.4.4
Note: you may need to restart the kernel to use updated packages.
Collecting numpy==1.26
  Using cached numpy-1.26.0-cp311-cp311-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.0-cp311-cp311-win_amd64.whl (15.8 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.4
    Uninstalling numpy-2.4.4:
      Successfully uninstalled numpy-2.4.4
Successfully installed numpy-1.26.0
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyannote-core 6.0.1 requires numpy>=2.0, but you have numpy 1.26.0 which is incompatible.
pyannote-metrics 4.0.0 requires numpy>=2.2.2, but you have numpy 1.26.0 which is incompatible.
scipy 1.17.1 requires numpy<2.7,>=1.26.4, but you have numpy 1.26.0 which is incompatible.

In [1]:
import sys
print(sys.executable)

c:\Users\a\LLM\ch05dia\Scripts\python.exe

In [2]:
from dotenv import load_dotenv
import os
from pyannote.audio import Pipeline

load_dotenv("../../.env", override=True)

hf_token = os.getenv("HF_TOKEN")

print("토큰 읽힘 여부:", hf_token is not None)

diarization_pipeline = Pipeline.from_pretrained(
    "pyannote/speaker-diarization-3.1",
    use_auth_token=hf_token
)

c:\Users\a\LLM\ch05dia\Lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")

토큰 읽힘 여부: True

c:\Users\a\LLM\ch05dia\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:43: UserWarning: torchaudio._backend.get_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  backend = torchaudio.get_audio_backend()
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
c:\Users\a\LLM\ch05dia\Lib\site-packages\speechbrain\utils\torch_audio_backend.py:22: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
c:\Users\a\LLM\ch05dia\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:53: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend(backend)
c:\Users\a\LLM\ch05dia\Lib\site-packages\pyannote\audio\tasks\segmentation\mixins.py:37: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
  from torchaudio.backend.common import AudioMetaData

In [3]:
diarization = diarization_pipeline("../audio/lsy_audio_2023_58s_16k.wav")

for turn, _, speaker in diarization.itertracks(yield_label=True):
    print(f"{turn.start:.1f}s ~ {turn.end:.1f}s: {speaker}")

0.2s ~ 0.9s: SPEAKER_00
1.4s ~ 6.4s: SPEAKER_00
7.0s ~ 10.5s: SPEAKER_00
11.0s ~ 16.7s: SPEAKER_00
17.2s ~ 21.6s: SPEAKER_00
22.0s ~ 31.8s: SPEAKER_00
32.2s ~ 37.4s: SPEAKER_00
38.1s ~ 39.9s: SPEAKER_00
40.1s ~ 47.2s: SPEAKER_00
47.6s ~ 48.6s: SPEAKER_00
49.8s ~ 56.1s: SPEAKER_00
57.0s ~ 58.0s: SPEAKER_00

In [8]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

diarization_pipeline.to(device)

print(f"Using device: {device}")

Using device: cpu

In [13]:
from pathlib import Path

audio_input = Path("../audio/싼기타_비싼기타_16k.wav")
output_rttm = "싼기타_비싼기타.rttm"

if "diarization_pipeline" not in globals():
    print("변수 'diarization_pipeline'이 생성되지 않아 실행을 중단합니다.")
else:
    print(f"화자 분리 시작: {audio_input}")

    try:
        diarization = diarization_pipeline(str(audio_input))

        with open(output_rttm, "w", encoding="utf-8") as rttm:
            diarization.write_rttm(rttm)

        print(f"성공! 결과 파일: {output_rttm}")

        for turn, _, speaker in diarization.itertracks(yield_label=True):
            print(f"[{turn.start:.1f}s - {turn.end:.1f}s] Speaker: {speaker}")

    except Exception as e:
        print(f"실행 중 오류 발생: {e}")

화자 분리 시작: ..\audio\싼기타_비싼기타_16k.wav
성공! 결과 파일: 싼기타_비싼기타.rttm
[1.0s - 6.8s] Speaker: SPEAKER_01
[7.4s - 11.4s] Speaker: SPEAKER_01
[11.8s - 16.7s] Speaker: SPEAKER_01
[17.2s - 27.9s] Speaker: SPEAKER_01
[28.7s - 30.2s] Speaker: SPEAKER_01
[32.4s - 33.2s] Speaker: SPEAKER_00
[33.6s - 37.1s] Speaker: SPEAKER_00
[37.6s - 41.4s] Speaker: SPEAKER_00
[41.6s - 42.7s] Speaker: SPEAKER_00
[41.7s - 42.4s] Speaker: SPEAKER_01
[42.7s - 44.0s] Speaker: SPEAKER_01
[45.8s - 46.4s] Speaker: SPEAKER_00
[46.9s - 50.5s] Speaker: SPEAKER_00
[51.0s - 55.1s] Speaker: SPEAKER_00
[55.2s - 59.5s] Speaker: SPEAKER_00
[60.0s - 64.9s] Speaker: SPEAKER_00
[65.5s - 67.1s] Speaker: SPEAKER_00
[67.2s - 79.0s] Speaker: SPEAKER_01
[79.2s - 82.8s] Speaker: SPEAKER_01
[84.6s - 87.1s] Speaker: SPEAKER_00
[87.2s - 91.1s] Speaker: SPEAKER_00
[91.8s - 97.4s] Speaker: SPEAKER_00
[97.9s - 102.6s] Speaker: SPEAKER_00
[103.5s - 114.6s] Speaker: SPEAKER_01
[115.1s - 117.5s] Speaker: SPEAKER_01
[119.7s - 120.5s] Speaker: SPEAKER_00
[120.8s - 127.5s] Speaker: SPEAKER_00
[128.2s - 133.7s] Speaker: SPEAKER_00
[134.2s - 138.7s] Speaker: SPEAKER_00
[139.3s - 142.7s] Speaker: SPEAKER_01
[143.2s - 143.8s] Speaker: SPEAKER_01
[144.0s - 146.7s] Speaker: SPEAKER_01
[146.8s - 169.0s] Speaker: SPEAKER_01
[170.9s - 176.1s] Speaker: SPEAKER_00
[176.5s - 184.6s] Speaker: SPEAKER_00
[185.1s - 192.3s] Speaker: SPEAKER_00
[192.3s - 193.7s] Speaker: SPEAKER_01
[192.8s - 193.5s] Speaker: SPEAKER_00
[193.9s - 216.6s] Speaker: SPEAKER_01
[218.6s - 222.9s] Speaker: SPEAKER_00
[223.4s - 228.9s] Speaker: SPEAKER_00
[229.6s - 233.0s] Speaker: SPEAKER_00
[233.4s - 237.8s] Speaker: SPEAKER_00
[238.1s - 238.7s] Speaker: SPEAKER_01
[238.2s - 239.4s] Speaker: SPEAKER_00
[239.9s - 240.6s] Speaker: SPEAKER_01
[240.3s - 241.0s] Speaker: SPEAKER_00
[241.0s - 247.9s] Speaker: SPEAKER_01
[248.2s - 251.3s] Speaker: SPEAKER_01
[253.7s - 257.6s] Speaker: SPEAKER_00
[258.1s - 262.3s] Speaker: SPEAKER_00
[262.7s - 267.5s] Speaker: SPEAKER_00
[268.1s - 271.5s] Speaker: SPEAKER_00
[272.1s - 276.2s] Speaker: SPEAKER_01
[276.7s - 282.9s] Speaker: SPEAKER_01
[283.3s - 290.8s] Speaker: SPEAKER_01
[291.0s - 304.5s] Speaker: SPEAKER_01
[307.0s - 311.2s] Speaker: SPEAKER_00
[311.6s - 318.8s] Speaker: SPEAKER_00
[319.4s - 326.0s] Speaker: SPEAKER_00
[326.4s - 331.0s] Speaker: SPEAKER_01
[331.4s - 335.5s] Speaker: SPEAKER_01
[337.5s - 342.7s] Speaker: SPEAKER_00
[343.2s - 347.2s] Speaker: SPEAKER_00
[347.6s - 352.3s] Speaker: SPEAKER_00
[352.6s - 355.9s] Speaker: SPEAKER_00
[356.3s - 364.0s] Speaker: SPEAKER_01
[366.0s - 366.4s] Speaker: SPEAKER_00
[366.7s - 371.6s] Speaker: SPEAKER_00
[371.9s - 378.6s] Speaker: SPEAKER_00
[379.1s - 381.4s] Speaker: SPEAKER_00
[382.2s - 383.7s] Speaker: SPEAKER_01
[385.7s - 387.5s] Speaker: SPEAKER_00
[387.9s - 390.6s] Speaker: SPEAKER_00
[391.1s - 394.9s] Speaker: SPEAKER_00
[395.3s - 397.2s] Speaker: SPEAKER_00
[397.6s - 399.1s] Speaker: SPEAKER_01
[401.4s - 403.6s] Speaker: SPEAKER_00
[404.0s - 406.6s] Speaker: SPEAKER_00
[407.4s - 408.3s] Speaker: SPEAKER_01
[410.1s - 412.0s] Speaker: SPEAKER_00
[412.4s - 414.0s] Speaker: SPEAKER_00
[414.5s - 417.4s] Speaker: SPEAKER_00
[417.8s - 421.2s] Speaker: SPEAKER_01
[423.6s - 424.4s] Speaker: SPEAKER_00
[424.7s - 428.3s] Speaker: SPEAKER_00
[428.5s - 429.3s] Speaker: SPEAKER_00

In [15]:
import pandas as pd
rttm_path = "../audio/싼기타_비싼기타.rttm"

df_rttm = pd.read_csv(
    rttm_path, # rttm 파일 경로
    sep=r"\s+", # 구분자는 띄어쓰기
    header=None, # 헤더는 없음
    names=['type', 'file', 'chnl', 'start', 'duration', 'C1', 'C2', 'speaker_id', 'C3', 'C4']
)

display(df_rttm)

       type      file  chnl    start  duration  C1  C2  speaker_id  C3  C4
0   SPEAKER  싼기타_비싼기타     1    0.993     5.805 NaN NaN  SPEAKER_01 NaN NaN
1   SPEAKER  싼기타_비싼기타     1    7.405     3.983 NaN NaN  SPEAKER_01 NaN NaN
2   SPEAKER  싼기타_비싼기타     1   11.759     4.927 NaN NaN  SPEAKER_01 NaN NaN
3   SPEAKER  싼기타_비싼기타     1   17.210    10.665 NaN NaN  SPEAKER_01 NaN NaN
4   SPEAKER  싼기타_비싼기타     1   28.668     1.536 NaN NaN  SPEAKER_01 NaN NaN
..      ...       ...   ...      ...       ...  ..  ..         ...  ..  ..
83  SPEAKER  싼기타_비싼기타     1  414.481     2.970 NaN NaN  SPEAKER_00 NaN NaN
84  SPEAKER  싼기타_비싼기타     1  417.755     3.476 NaN NaN  SPEAKER_01 NaN NaN
85  SPEAKER  싼기타_비싼기타     1  423.644     0.776 NaN NaN  SPEAKER_00 NaN NaN
86  SPEAKER  싼기타_비싼기타     1  424.741     3.527 NaN NaN  SPEAKER_00 NaN NaN
87  SPEAKER  싼기타_비싼기타     1  428.504     0.844 NaN NaN  SPEAKER_00 NaN NaN

[88 rows x 10 columns]

In [16]:
# start + duration을 end로 변환
df_rttm['end'] = df_rttm['start'] + df_rttm['duration']

display(df_rttm)

,type,file,chnl,start,duration,C1,C2,speaker_id,C3,C4,end
0,SPEAKER,싼기타_비싼기타,1,0.993,5.805,NaN,NaN,SPEAKER_01,NaN,NaN,6.798
1,SPEAKER,싼기타_비싼기타,1,7.405,3.983,NaN,NaN,SPEAKER_01,NaN,NaN,11.388
2,SPEAKER,싼기타_비싼기타,1,11.759,4.927,NaN,NaN,SPEAKER_01,NaN,NaN,16.686
3,SPEAKER,싼기타_비싼기타,1,17.210,10.665,NaN,NaN,SPEAKER_01,NaN,NaN,27.875
4,SPEAKER,싼기타_비싼기타,1,28.668,1.536,NaN,NaN,SPEAKER_01,NaN,NaN,30.204
...,...,...,...,...,...,...,...,...,...,...,...
83,SPEAKER,싼기타_비싼기타,1,414.481,2.970,NaN,NaN,SPEAKER_00,NaN,NaN,417.451
84,SPEAKER,싼기타_비싼기타,1,417.755,3.476,NaN,NaN,SPEAKER_01,NaN,NaN,421.231
85,SPEAKER,싼기타_비싼기타,1,423.644,0.776,NaN,NaN,SPEAKER_00,NaN,NaN,424.420
86,SPEAKER,싼기타_비싼기타,1,424.741,3.527,NaN,NaN,SPEAKER_00,NaN,NaN,428.268
87,SPEAKER,싼기타_비싼기타,1,428.504,0.844,NaN,NaN,SPEAKER_00,NaN,NaN,429.348

In [17]:
df_rttm["number"] = None	# number 열 만들고 None으로 초기화
df_rttm.at[0, "number"] = 0

display(df_rttm)

,type,file,chnl,start,duration,C1,C2,speaker_id,C3,C4,end,number
0,SPEAKER,싼기타_비싼기타,1,0.993,5.805,NaN,NaN,SPEAKER_01,NaN,NaN,6.798,0
1,SPEAKER,싼기타_비싼기타,1,7.405,3.983,NaN,NaN,SPEAKER_01,NaN,NaN,11.388,None
2,SPEAKER,싼기타_비싼기타,1,11.759,4.927,NaN,NaN,SPEAKER_01,NaN,NaN,16.686,None
3,SPEAKER,싼기타_비싼기타,1,17.210,10.665,NaN,NaN,SPEAKER_01,NaN,NaN,27.875,None
4,SPEAKER,싼기타_비싼기타,1,28.668,1.536,NaN,NaN,SPEAKER_01,NaN,NaN,30.204,None
...,...,...,...,...,...,...,...,...,...,...,...,...
83,SPEAKER,싼기타_비싼기타,1,414.481,2.970,NaN,NaN,SPEAKER_00,NaN,NaN,417.451,None
84,SPEAKER,싼기타_비싼기타,1,417.755,3.476,NaN,NaN,SPEAKER_01,NaN,NaN,421.231,None
85,SPEAKER,싼기타_비싼기타,1,423.644,0.776,NaN,NaN,SPEAKER_00,NaN,NaN,424.420,None
86,SPEAKER,싼기타_비싼기타,1,424.741,3.527,NaN,NaN,SPEAKER_00,NaN,NaN,428.268,None
87,SPEAKER,싼기타_비싼기타,1,428.504,0.844,NaN,NaN,SPEAKER_00,NaN,NaN,429.348,None

In [18]:
for i in range(1, len(df_rttm)):
    if df_rttm.at[i, "speaker_id"] != df_rttm.at[i-1, "speaker_id"]:
        df_rttm.at[i, "number"] = df_rttm.at[i-1, "number"] + 1
    else:
        df_rttm.at[i, "number"] = df_rttm.at[i-1, "number"]

display(df_rttm.head(10))

,type,file,chnl,start,duration,C1,C2,speaker_id,C3,C4,end,number
0,SPEAKER,싼기타_비싼기타,1,0.993,5.805,NaN,NaN,SPEAKER_01,NaN,NaN,6.798,0
1,SPEAKER,싼기타_비싼기타,1,7.405,3.983,NaN,NaN,SPEAKER_01,NaN,NaN,11.388,0
2,SPEAKER,싼기타_비싼기타,1,11.759,4.927,NaN,NaN,SPEAKER_01,NaN,NaN,16.686,0
3,SPEAKER,싼기타_비싼기타,1,17.210,10.665,NaN,NaN,SPEAKER_01,NaN,NaN,27.875,0
4,SPEAKER,싼기타_비싼기타,1,28.668,1.536,NaN,NaN,SPEAKER_01,NaN,NaN,30.204,0
5,SPEAKER,싼기타_비싼기타,1,32.414,0.759,NaN,NaN,SPEAKER_00,NaN,NaN,33.173,1
6,SPEAKER,싼기타_비싼기타,1,33.545,3.561,NaN,NaN,SPEAKER_00,NaN,NaN,37.106,1
7,SPEAKER,싼기타_비싼기타,1,37.628,3.763,NaN,NaN,SPEAKER_00,NaN,NaN,41.391,1
8,SPEAKER,싼기타_비싼기타,1,41.611,1.097,NaN,NaN,SPEAKER_00,NaN,NaN,42.708,1
9,SPEAKER,싼기타_비싼기타,1,41.645,0.810,NaN,NaN,SPEAKER_01,NaN,NaN,42.455,2

In [19]:
df_rttm_grouped = df_rttm.groupby("number").agg(
    start=pd.NamedAgg(column='start', aggfunc='min'),
    end=pd.NamedAgg(column='end', aggfunc='max'),
    speaker_id=pd.NamedAgg(column='speaker_id', aggfunc='first')
)

display(df_rttm_grouped)

          start      end  speaker_id
number
0         0.993   30.204  SPEAKER_01
1        32.414   42.708  SPEAKER_00
2        41.645   44.024  SPEAKER_01
3        45.813   67.109  SPEAKER_00
4        67.227   82.786  SPEAKER_01
5        84.659  102.564  SPEAKER_00
6       103.492  117.532  SPEAKER_01
7       119.759  138.676  SPEAKER_00
8       139.351  168.967  SPEAKER_01
9       170.907  192.321  SPEAKER_00
10      192.322  193.689  SPEAKER_01
11      192.760  193.503  SPEAKER_00
12      193.823  216.571  SPEAKER_01
13      218.579  238.120  SPEAKER_00
14      238.120  238.677  SPEAKER_01
15      238.188  239.352  SPEAKER_00
16      239.858  240.651  SPEAKER_01
17      240.297  241.006  SPEAKER_00
18      241.040  251.334  SPEAKER_01
19      253.696  271.550  SPEAKER_00
20      272.140  304.557  SPEAKER_01
21      306.970  326.022  SPEAKER_00
22      326.360  335.472  SPEAKER_01
23      337.548  355.925  SPEAKER_00
24      356.245  363.974  SPEAKER_01
25      365.982  381.423  SPEAKER_00
26      382.165  383.734  SPEAKER_01
27      385.726  397.184  SPEAKER_00
28      397.623  399.108  SPEAKER_01
29      401.437  406.601  SPEAKER_00
30      407.326  408.338  SPEAKER_01
31      410.093  417.451  SPEAKER_00
32      417.755  421.231  SPEAKER_01
33      423.644  429.348  SPEAKER_00

In [20]:
df_rttm_grouped["duration"] = df_rttm_grouped["end"] - df_rttm_grouped["start"]
df_rttm_grouped = df_rttm_grouped.reset_index(drop=True)
display(df_rttm_grouped)

      start      end  speaker_id  duration
0     0.993   30.204  SPEAKER_01    29.211
1    32.414   42.708  SPEAKER_00    10.294
2    41.645   44.024  SPEAKER_01     2.379
3    45.813   67.109  SPEAKER_00    21.296
4    67.227   82.786  SPEAKER_01    15.559
5    84.659  102.564  SPEAKER_00    17.905
6   103.492  117.532  SPEAKER_01    14.040
7   119.759  138.676  SPEAKER_00    18.917
8   139.351  168.967  SPEAKER_01    29.616
9   170.907  192.321  SPEAKER_00    21.414
10  192.322  193.689  SPEAKER_01     1.367
11  192.760  193.503  SPEAKER_00     0.743
12  193.823  216.571  SPEAKER_01    22.748
13  218.579  238.120  SPEAKER_00    19.541
14  238.120  238.677  SPEAKER_01     0.557
15  238.188  239.352  SPEAKER_00     1.164
16  239.858  240.651  SPEAKER_01     0.793
17  240.297  241.006  SPEAKER_00     0.709
18  241.040  251.334  SPEAKER_01    10.294
19  253.696  271.550  SPEAKER_00    17.854
20  272.140  304.557  SPEAKER_01    32.417
21  306.970  326.022  SPEAKER_00    19.052
22  326.360  335.472  SPEAKER_01     9.112
23  337.548  355.925  SPEAKER_00    18.377
24  356.245  363.974  SPEAKER_01     7.729
25  365.982  381.423  SPEAKER_00    15.441
26  382.165  383.734  SPEAKER_01     1.569
27  385.726  397.184  SPEAKER_00    11.458
28  397.623  399.108  SPEAKER_01     1.485
29  401.437  406.601  SPEAKER_00     5.164
30  407.326  408.338  SPEAKER_01     1.012
31  410.093  417.451  SPEAKER_00     7.358
32  417.755  421.231  SPEAKER_01     3.476
33  423.644  429.348  SPEAKER_00     5.704

In [21]:
df_rttm_grouped.to_csv(
    "싼기타_비싼기타_rttm.csv",
    sep=',',
    index=False
)